In [12]:
import torch
import numpy as np
import time
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [37]:
start_time=time.time()
# matrix opertions done here
zeros=torch.zeros(1,1)
end_time=time.time()

elapsed_time=end_time-start_time
print(f"{elapsed_time:.10f}")

1.1357390881


In [19]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [18]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.02493405
0.11668873


In [24]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)


tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])


In [25]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [34]:
out = torch.tril(torch.ones(5, 5))
out
#left Identity tirangle
# talking to history what are the future predictions

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [35]:
out = torch.triu(torch.ones(5, 5))
out
# right upper  identity triangle
#


tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [36]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out
# basically we are calculating the powers like o^1 if 0 and if 1^-inf=0

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [29]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [30]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [38]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
import torch.nn as nn
# nn layer is the way to give prameters and they are learnable if passed with nn
sample=torch.tensor([10.,10.,10.])
# we will use this for learning the keys, queries and values in transformers first layer
linear=nn.Linear(3,3,bias=False)
print(linear(sample)) 

tensor([  3.8187,  -1.4978, -11.9467], grad_fn=<SqueezeBackward4>)


In [48]:
import torch.nn.functional as F # for all the activation function we need this
#create tensor to work with
t1=torch.tensor([1.0,2.0,3.0])
softmax_output=F.softmax(t1,dim=0) #use the softmax with only tensor needed
print(softmax_output)


tensor([0.0900, 0.2447, 0.6652])


In [53]:
# Initialize an embedding layer
vocab_size = 1000
embedding_dim = 10
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)


torch.Size([3, 10])
tensor([[-1.9152,  1.4207, -0.1508,  1.0636, -0.9882,  0.0530, -0.0073, -0.3555,
          0.2112, -2.4129],
        [ 0.7260,  1.0625, -0.1664,  0.7667, -1.0894,  0.3828, -0.4461, -1.0813,
         -0.2224,  0.8658],
        [-0.8085, -0.3144,  1.0027,  0.6413, -1.0144, -0.4999, -1.1239,  0.2259,
          0.2569, -1.2042]], grad_fn=<EmbeddingBackward0>)


In [62]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [70]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [73]:
a=torch.rand(2,3,5)
print(a.shape)
x,y,z=a.shape
a=a.view(x,y,z)
print(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [57]:
#randint=torch.randint(-100,100,(6,))
#randint

In [23]:
# tensor=torch.tensor([[0.1,1.2],[2.2,3.1],[5.1,8.4]])
# tensor

In [24]:
# ones=torch.ones(3,4)
# ones

In [25]:
# zeros=torch.zeros(2,3)
# zeros

In [26]:
# input=torch.empty(2,3)
# input

In [27]:
# arange=torch.arange(10)
# arange

In [28]:
# linspace=torch.linspace(3,10,steps=5)
# linspace

In [29]:
# logspace=torch.logspace(start=-10,end=10,steps=5)
# logspace

In [30]:
# eye=torch.eye(5)
# eye
# # reduced echelon form 

In [31]:
# a=torch.empty((2,3),dtype=torch.int64)
# empty_like=torch.empty_like(a)
# empty_like